### ISSUE TITLE
mvn无法正常打包

### ISSUE THREAD

**Issue by hlgzhx** [citrucn/OaSys#5]
在oasys-master目录下执行mvn clean package时报错：
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.6.3:repackage (repackage) on project oasys-common: Execution repackage of goal org.springframework.boot:spring-boot-maven-plugin:2.6.3:repackage failed: Unable to find main class -> [Help 1]

**Comment by Furinai** [comment]
先得把common模块安装，在根模块执行mvn package应该就没问题，不行就先在oasys-common执行mvn install
